version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8080"
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/public/data
    environment:
      - NODE_ENV=development
      - VITE_APP_DATA_PATH=/data

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    volumes:
      - ./scraper:/app
      - ./data:/data
    # Only run the scraper on demand
    profiles:
      - scraper

# No longer need a named volume as we're using a local directory
# volumes:
#   data-volume:
#     # Named volume to share data between containers
