
version: '3'

services:
  vasaloppet-analytics:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html/public
    # Add healthcheck to verify the container is running correctly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
